"""
Django settings for backend project.
Generated by 'django-admin startproject' using Django 5.2.5.
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# --- Quick-start development settings (NOT for production) ---
SECRET_KEY = "django-insecure-e!gjsm$y#2p)ji2&9$=50_q^ap_od*l5@8wln#i^%y7!(qwf)-"
DEBUG = True

# For local development these are fine; add your server hostnames in prod.
ALLOWED_HOSTS = ["127.0.0.1", "localhost"]

# --- Application definition ---
INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",  # static files app

    # your apps
    "users.apps.UsersConfig",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "backend.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        # project-level templates directory
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,  # also loads app_name/templates/ automatically
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "backend.wsgi.application"

# --- Database (SQLite for dev) ---
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}

# --- Password validation ---
AUTH_PASSWORD_VALIDATORS = [
    {"NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"},
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]

# --- Internationalization ---
LANGUAGE_CODE = "en-us"
TIME_ZONE = "Asia/Dhaka"
USE_I18N = True
USE_TZ = True

# --- Static files (CSS, JavaScript, Images) ---
# URL that serves static files
STATIC_URL = "static/"

# Where your development/static source files live (must exist)
# e.g. BASE_DIR/static/home/css/home.css, static/splash_screens/...
STATICFILES_DIRS = [BASE_DIR / "static"]

# Where 'collectstatic' will gather files for production (ok to keep now)
STATIC_ROOT = BASE_DIR / "staticfiles"

# --- Media files (user uploads) ---
MEDIA_URL = "media/"
MEDIA_ROOT = BASE_DIR / "media"

# --- Auth redirects ---
LOGIN_URL = "login"
LOGIN_REDIRECT_URL = "dashboard"
LOGOUT_REDIRECT_URL = "login"

# --- Email backend ---
# For development, print emails to the console.
EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"

# --- Default primary key field type ---
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
